INSERT INTO `Settings` (`key`, `value`) VALUES ('site_name', 'Moshisa Jadeite');
INSERT INTO `Settings` (`key`, `value`) VALUES ('footer_info', '© 2024 Moshisa Jadeite');
INSERT INTO `Settings` (`key`, `value`) VALUES ('phone_number', '0814630386');
INSERT INTO `Settings` (`key`, `value`) VALUES ('banner_title', 'Vẻ đẹp tinh khôi từ ngọc');
INSERT INTO `Settings` (`key`, `value`) VALUES ('banner_subtitle', 'Khám phá những bộ sưu tập trang sức ngọc được chế tác tinh xảo, mang lại vẻ đẹp sang trọng và quý phái.');
INSERT INTO `Settings` (`key`, `value`) VALUES ('banner_button_text', 'Xem thêm...');
INSERT INTO `Settings` (`key`, `value`) VALUES ('banner_button_link', '#');
INSERT INTO `Settings` (`key`, `value`) VALUES ('banner_article_link', '');
INSERT INTO `Settings` (`key`, `value`) VALUES ('featured_products_title', NULL);
INSERT INTO `Settings` (`key`, `value`) VALUES ('testimonials_title', NULL);
INSERT INTO `Settings` (`key`, `value`) VALUES ('footer_about_us_text', 'Moshisa-jadeite.com chuyên bán phỉ thúy Type A. ');
INSERT INTO `Settings` (`key`, `value`) VALUES ('about_us_business_info', NULL);
INSERT INTO `Settings` (`key`, `value`) VALUES ('about_us_phone', '0814 630 386 ');
INSERT INTO `Settings` (`key`, `value`) VALUES ('about_us_address', '4449 Nguyễn Cửu Phú, Tân Tạo A, Bình Tân, Hồ Chí Minh');
INSERT INTO `Settings` (`key`, `value`) VALUES ('about_us_email', 'moshisajadeite1610@gmail.com');
INSERT INTO `Settings` (`key`, `value`) VALUES ('color_primary', '#085e08');
INSERT INTO `Settings` (`key`, `value`) VALUES ('color_accent', '#c5a47e');
INSERT INTO `Settings` (`key`, `value`) VALUES ('payment_partners', '[]');
INSERT INTO `Settings` (`key`, `value`) VALUES ('shipping_partners', '[]');
INSERT INTO `Settings` (`key`, `value`) VALUES ('logo_url', '/uploads/logo-1760784702373-314720465.jpg');
INSERT INTO `Settings` (`key`, `value`) VALUES ('banner_image_url', '/uploads/banner_image-1760692759104-690070515.jpg');
